# Terminal
set-option -g default-terminal "tmux-256color"
set-option -g terminal-overrides ",xterm-256color:RGB"

# Prefix: Ctrl+Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# General
set -g base-index 1
set -g renumber-windows on
set -g set-clipboard on
set -g mouse on
set -g status-position top

# Plugins (TPM)
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "catppuccin/tmux"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "tmux-plugins/tmux-cpu"
set -g @plugin "tmux-plugins/tmux-battery"

# Catppuccin options
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Status
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Window navigation with Ctrl+Shift+h/l
bind -n C-S-h previous-window
bind -n C-S-l next-window

# TPM bootstrap
run "~/.tmux/plugins/tpm/tpm"
